[workspace]
members = ["server"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/dorialang/doria-language-server"
version = "2026.3.1-canary"

[workspace.dependencies]
doriac = { git = "https://github.com/dorialang/doria", rev = "c37663ae9b5e2662f22b1558af51854ddd79e7aa", default-features = false }
serde_json = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"
lto = "thin"
