[workspace]
members = ["server"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/dorialang/doria-language-server"
version = "2026.3.1-canary"

[workspace.dependencies]
doriac = { git = "https://github.com/dorialang/doria", rev = "3c5b211d7300afc20301e2b20d32b56b4fe9ae5e", default-features = false }
serde_json = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"
lto = "thin"
