plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.4.10'
    id 'org.jetbrains.intellij.platform'
}

group = 'dev.doria'
version = '2026.03.1-canary'

dependencies {
    testImplementation 'junit:junit:4.13.2'

    intellijPlatform {
        create(
            providers.gradleProperty('platformType'),
            providers.gradleProperty('platformVersion')
        )
        testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform.INSTANCE)
    }
}

intellijPlatform {
    buildSearchableOptions = false

    pluginConfiguration {
        ideaVersion {
            sinceBuild = '252'
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile).configureEach {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    }
}

def cleanPluginDistributions = tasks.register('cleanPluginDistributions', Delete) {
    delete layout.buildDirectory.dir('distributions')
}

tasks.named('buildPlugin') {
    dependsOn cleanPluginDistributions
    archiveFileName = "doria-intellij-plugin-${project.version}.zip"
}
